#############################################################################
# Makefile for building: dieptemeting
# Generated by qmake (2.01a) (Qt 4.7.0) on: Wed Dec 14 14:48:57 2011
# Project:  dieptemeting.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile dieptemeting.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -march=i486 -mtune=i686 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -march=i486 -mtune=i686 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/lib/qt/mkspecs/linux-g++ -I. -I/usr/lib/qt/include/QtCore -I/usr/lib/qt/include/QtGui -I/usr/lib/qt/include -I. -Ilijn -Ilistsel -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/usr/lib/qt/lib
LIBS          = $(SUBLIBS)  -L/usr/lib/qt/lib -lQtGui -L/usr/lib/qt/lib -L/usr/X11R6/lib -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = dieptemeting.cpp \
		driehoek.cpp \
		meting.cpp \
		punt.cpp \
		strook.cpp \
		vaart.cpp \
		lijn/dieptelijnen.cpp \
		lijn/dieptemeting.cpp \
		lijn/driehoek.cpp \
		lijn/meting.cpp \
		lijn/punt.cpp \
		lijn/strook.cpp \
		lijn/vaart.cpp \
		lijn/vlak.cpp \
		lijn/zijde.cpp \
		lijn/zijden.cpp \
		list/dieptemeting.cpp \
		list/driehoek.cpp \
		list/meting.cpp \
		list/punt.cpp \
		list/strook.cpp \
		list/vaart.cpp \
		listsel/dieptemeting.cpp \
		listsel/driehoek.cpp \
		listsel/meting.cpp \
		listsel/punt.cpp \
		listsel/strook.cpp \
		listsel/vaart.cpp \
		omuis/dieptemeting.cpp \
		omuis/driehoek.cpp \
		omuis/meting.cpp \
		omuis/punt.cpp \
		omuis/qparser.cpp \
		omuis/strook.cpp \
		omuis/vaart.cpp moc_dieptemeting.cpp
OBJECTS       = dieptemeting.o \
		driehoek.o \
		meting.o \
		punt.o \
		strook.o \
		vaart.o \
		dieptelijnen.o \
		dieptemeting.o \
		driehoek.o \
		meting.o \
		punt.o \
		strook.o \
		vaart.o \
		vlak.o \
		zijde.o \
		zijden.o \
		dieptemeting.o \
		driehoek.o \
		meting.o \
		punt.o \
		strook.o \
		vaart.o \
		dieptemeting.o \
		driehoek.o \
		meting.o \
		punt.o \
		strook.o \
		vaart.o \
		dieptemeting.o \
		driehoek.o \
		meting.o \
		punt.o \
		qparser.o \
		strook.o \
		vaart.o \
		moc_dieptemeting.o
DIST          = /usr/lib/qt/mkspecs/common/g++.conf \
		/usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_phonon.pri \
		/usr/lib/qt/mkspecs/modules/qt_webkit_version.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		/usr/lib/qt/mkspecs/features/release.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/warn_on.prf \
		/usr/lib/qt/mkspecs/features/qt.prf \
		/usr/lib/qt/mkspecs/features/unix/thread.prf \
		/usr/lib/qt/mkspecs/features/moc.prf \
		/usr/lib/qt/mkspecs/features/resources.prf \
		/usr/lib/qt/mkspecs/features/uic.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		/usr/lib/qt/mkspecs/features/include_source_dir.prf \
		dieptemeting.pro
QMAKE_TARGET  = dieptemeting
DESTDIR       = 
TARGET        = dieptemeting

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: dieptemeting.pro  /usr/lib/qt/mkspecs/linux-g++/qmake.conf /usr/lib/qt/mkspecs/common/g++.conf \
		/usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_phonon.pri \
		/usr/lib/qt/mkspecs/modules/qt_webkit_version.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		/usr/lib/qt/mkspecs/features/release.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/warn_on.prf \
		/usr/lib/qt/mkspecs/features/qt.prf \
		/usr/lib/qt/mkspecs/features/unix/thread.prf \
		/usr/lib/qt/mkspecs/features/moc.prf \
		/usr/lib/qt/mkspecs/features/resources.prf \
		/usr/lib/qt/mkspecs/features/uic.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		/usr/lib/qt/mkspecs/features/include_source_dir.prf \
		/usr/lib/qt/lib/libQtGui.prl \
		/usr/lib/qt/lib/libQtCore.prl
	$(QMAKE) -o Makefile dieptemeting.pro
/usr/lib/qt/mkspecs/common/g++.conf:
/usr/lib/qt/mkspecs/common/unix.conf:
/usr/lib/qt/mkspecs/common/linux.conf:
/usr/lib/qt/mkspecs/qconfig.pri:
/usr/lib/qt/mkspecs/modules/qt_phonon.pri:
/usr/lib/qt/mkspecs/modules/qt_webkit_version.pri:
/usr/lib/qt/mkspecs/features/qt_functions.prf:
/usr/lib/qt/mkspecs/features/qt_config.prf:
/usr/lib/qt/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt/mkspecs/features/default_pre.prf:
/usr/lib/qt/mkspecs/features/release.prf:
/usr/lib/qt/mkspecs/features/default_post.prf:
/usr/lib/qt/mkspecs/features/warn_on.prf:
/usr/lib/qt/mkspecs/features/qt.prf:
/usr/lib/qt/mkspecs/features/unix/thread.prf:
/usr/lib/qt/mkspecs/features/moc.prf:
/usr/lib/qt/mkspecs/features/resources.prf:
/usr/lib/qt/mkspecs/features/uic.prf:
/usr/lib/qt/mkspecs/features/yacc.prf:
/usr/lib/qt/mkspecs/features/lex.prf:
/usr/lib/qt/mkspecs/features/include_source_dir.prf:
/usr/lib/qt/lib/libQtGui.prl:
/usr/lib/qt/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile dieptemeting.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/dieptemeting1.0.0 || $(MKDIR) .tmp/dieptemeting1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/dieptemeting1.0.0/ && $(COPY_FILE) --parents driehoek.h insprong.h meting.h punt.h strook.h vaart.h lijn/alles.h lijn/dieptelijnen.h lijn/driehoek.h lijn/insprong.h lijn/meting.h lijn/punt.h lijn/strook.h lijn/vaart.h lijn/vlak.h lijn/zijde.h lijn/zijden.h list/driehoek.h list/insprong.h list/meting.h list/punt.h list/strook.h list/vaart.h listsel/dieptemeting.h listsel/driehoek.h listsel/insprong.h listsel/meting.h listsel/punt.h listsel/strook.h listsel/vaart.h omuis/driehoek.h omuis/insprong.h omuis/meting.h omuis/punt.h omuis/strook.h omuis/vaart.h .tmp/dieptemeting1.0.0/ && $(COPY_FILE) --parents dieptemeting.cpp driehoek.cpp meting.cpp punt.cpp strook.cpp vaart.cpp lijn/dieptelijnen.cpp lijn/dieptemeting.cpp lijn/driehoek.cpp lijn/meting.cpp lijn/punt.cpp lijn/strook.cpp lijn/vaart.cpp lijn/vlak.cpp lijn/zijde.cpp lijn/zijden.cpp list/dieptemeting.cpp list/driehoek.cpp list/meting.cpp list/punt.cpp list/strook.cpp list/vaart.cpp listsel/dieptemeting.cpp listsel/driehoek.cpp listsel/meting.cpp listsel/punt.cpp listsel/strook.cpp listsel/vaart.cpp omuis/dieptemeting.cpp omuis/driehoek.cpp omuis/meting.cpp omuis/punt.cpp omuis/qparser.cpp omuis/strook.cpp omuis/vaart.cpp .tmp/dieptemeting1.0.0/ && (cd `dirname .tmp/dieptemeting1.0.0` && $(TAR) dieptemeting1.0.0.tar dieptemeting1.0.0 && $(COMPRESS) dieptemeting1.0.0.tar) && $(MOVE) `dirname .tmp/dieptemeting1.0.0`/dieptemeting1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/dieptemeting1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_dieptemeting.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_dieptemeting.cpp
moc_dieptemeting.cpp: listsel/vaart.h \
		listsel/meting.h \
		listsel/punt.h \
		listsel/strook.h \
		listsel/driehoek.h \
		listsel/dieptemeting.h
	/usr/lib/qt/bin/moc $(DEFINES) $(INCPATH) listsel/dieptemeting.h -o moc_dieptemeting.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

dieptemeting.o: dieptemeting.cpp vaart.h \
		meting.h \
		punt.h \
		strook.h \
		driehoek.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dieptemeting.o dieptemeting.cpp

driehoek.o: driehoek.cpp driehoek.h \
		punt.h \
		insprong.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o driehoek.o driehoek.cpp

meting.o: meting.cpp meting.h \
		punt.h \
		insprong.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o meting.o meting.cpp

punt.o: punt.cpp punt.h \
		insprong.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o punt.o punt.cpp

strook.o: strook.cpp strook.h \
		driehoek.h \
		punt.h \
		insprong.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o strook.o strook.cpp

vaart.o: vaart.cpp vaart.h \
		meting.h \
		punt.h \
		strook.h \
		driehoek.h \
		insprong.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vaart.o vaart.cpp

dieptelijnen.o: lijn/dieptelijnen.cpp lijn/dieptelijnen.h \
		lijn/vaart.h \
		lijn/alles.h \
		lijn/meting.h \
		lijn/punt.h \
		lijn/driehoek.h \
		lijn/zijde.h \
		lijn/vlak.h \
		lijn/zijden.h \
		lijn/strook.h \
		lijn/insprong.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dieptelijnen.o lijn/dieptelijnen.cpp

dieptemeting.o: lijn/dieptemeting.cpp lijn/vaart.h \
		lijn/alles.h \
		lijn/meting.h \
		lijn/punt.h \
		lijn/driehoek.h \
		lijn/zijde.h \
		lijn/vlak.h \
		lijn/zijden.h \
		lijn/dieptelijnen.h \
		lijn/strook.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dieptemeting.o lijn/dieptemeting.cpp

driehoek.o: lijn/driehoek.cpp lijn/driehoek.h \
		lijn/punt.h \
		lijn/zijde.h \
		lijn/alles.h \
		lijn/vlak.h \
		lijn/zijden.h \
		lijn/dieptelijnen.h \
		lijn/vaart.h \
		lijn/meting.h \
		lijn/strook.h \
		lijn/insprong.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o driehoek.o lijn/driehoek.cpp

meting.o: lijn/meting.cpp lijn/meting.h \
		lijn/punt.h \
		lijn/insprong.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o meting.o lijn/meting.cpp

punt.o: lijn/punt.cpp lijn/punt.h \
		lijn/insprong.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o punt.o lijn/punt.cpp

strook.o: lijn/strook.cpp lijn/strook.h \
		lijn/driehoek.h \
		lijn/punt.h \
		lijn/zijde.h \
		lijn/alles.h \
		lijn/vlak.h \
		lijn/zijden.h \
		lijn/dieptelijnen.h \
		lijn/vaart.h \
		lijn/meting.h \
		lijn/insprong.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o strook.o lijn/strook.cpp

vaart.o: lijn/vaart.cpp lijn/vaart.h \
		lijn/alles.h \
		lijn/meting.h \
		lijn/punt.h \
		lijn/driehoek.h \
		lijn/zijde.h \
		lijn/vlak.h \
		lijn/zijden.h \
		lijn/dieptelijnen.h \
		lijn/strook.h \
		lijn/insprong.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vaart.o lijn/vaart.cpp

vlak.o: lijn/vlak.cpp lijn/vlak.h \
		lijn/driehoek.h \
		lijn/punt.h \
		lijn/zijde.h \
		lijn/alles.h \
		lijn/zijden.h \
		lijn/dieptelijnen.h \
		lijn/vaart.h \
		lijn/meting.h \
		lijn/strook.h \
		lijn/insprong.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vlak.o lijn/vlak.cpp

zijde.o: lijn/zijde.cpp lijn/zijde.h \
		lijn/alles.h \
		lijn/punt.h \
		lijn/vlak.h \
		lijn/driehoek.h \
		lijn/zijden.h \
		lijn/dieptelijnen.h \
		lijn/vaart.h \
		lijn/meting.h \
		lijn/strook.h \
		lijn/insprong.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o zijde.o lijn/zijde.cpp

zijden.o: lijn/zijden.cpp lijn/zijden.h \
		lijn/alles.h \
		lijn/punt.h \
		lijn/driehoek.h \
		lijn/zijde.h \
		lijn/vlak.h \
		lijn/dieptelijnen.h \
		lijn/vaart.h \
		lijn/meting.h \
		lijn/strook.h \
		lijn/insprong.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o zijden.o lijn/zijden.cpp

dieptemeting.o: list/dieptemeting.cpp list/vaart.h \
		list/meting.h \
		list/punt.h \
		list/strook.h \
		list/driehoek.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dieptemeting.o list/dieptemeting.cpp

driehoek.o: list/driehoek.cpp list/driehoek.h \
		list/punt.h \
		list/insprong.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o driehoek.o list/driehoek.cpp

meting.o: list/meting.cpp list/meting.h \
		list/punt.h \
		list/insprong.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o meting.o list/meting.cpp

punt.o: list/punt.cpp list/punt.h \
		list/insprong.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o punt.o list/punt.cpp

strook.o: list/strook.cpp list/strook.h \
		list/driehoek.h \
		list/punt.h \
		list/insprong.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o strook.o list/strook.cpp

vaart.o: list/vaart.cpp list/vaart.h \
		list/meting.h \
		list/punt.h \
		list/strook.h \
		list/driehoek.h \
		list/insprong.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vaart.o list/vaart.cpp

dieptemeting.o: listsel/dieptemeting.cpp listsel/dieptemeting.h \
		listsel/vaart.h \
		listsel/meting.h \
		listsel/punt.h \
		listsel/strook.h \
		listsel/driehoek.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dieptemeting.o listsel/dieptemeting.cpp

driehoek.o: listsel/driehoek.cpp listsel/driehoek.h \
		listsel/punt.h \
		listsel/insprong.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o driehoek.o listsel/driehoek.cpp

meting.o: listsel/meting.cpp listsel/meting.h \
		listsel/punt.h \
		listsel/insprong.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o meting.o listsel/meting.cpp

punt.o: listsel/punt.cpp listsel/punt.h \
		listsel/insprong.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o punt.o listsel/punt.cpp

strook.o: listsel/strook.cpp listsel/strook.h \
		listsel/meting.h \
		listsel/punt.h \
		listsel/driehoek.h \
		listsel/insprong.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o strook.o listsel/strook.cpp

vaart.o: listsel/vaart.cpp listsel/vaart.h \
		listsel/meting.h \
		listsel/punt.h \
		listsel/strook.h \
		listsel/driehoek.h \
		listsel/insprong.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vaart.o listsel/vaart.cpp

dieptemeting.o: omuis/dieptemeting.cpp omuis/vaart.h \
		omuis/meting.h \
		omuis/punt.h \
		omuis/strook.h \
		omuis/driehoek.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dieptemeting.o omuis/dieptemeting.cpp

driehoek.o: omuis/driehoek.cpp omuis/driehoek.h \
		omuis/punt.h \
		omuis/insprong.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o driehoek.o omuis/driehoek.cpp

meting.o: omuis/meting.cpp omuis/meting.h \
		omuis/punt.h \
		omuis/insprong.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o meting.o omuis/meting.cpp

punt.o: omuis/punt.cpp omuis/punt.h \
		omuis/insprong.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o punt.o omuis/punt.cpp

qparser.o: omuis/qparser.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qparser.o omuis/qparser.cpp

strook.o: omuis/strook.cpp omuis/strook.h \
		omuis/meting.h \
		omuis/punt.h \
		omuis/driehoek.h \
		omuis/insprong.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o strook.o omuis/strook.cpp

vaart.o: omuis/vaart.cpp omuis/vaart.h \
		omuis/meting.h \
		omuis/punt.h \
		omuis/strook.h \
		omuis/driehoek.h \
		omuis/insprong.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vaart.o omuis/vaart.cpp

moc_dieptemeting.o: moc_dieptemeting.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dieptemeting.o moc_dieptemeting.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

