######################################################################
# Automatically generated by qmake (1.07a) Sat May 27 22:36:50 2006
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += dieptemeting.h driehoek.h insprong.h meting.h punt.h strook.h vaart.h
SOURCES += dieptemeting.cpp \
           driehoek.cpp \
           meting.cpp \
           punt.cpp \
           strook.cpp \
           vaart.cpp
